GET http://localhost:5297/playergames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJvaGFuIiwic3ViIjoicm9oYW4iLCJqdGkiOiI3OGE3ODk0MyIsInJvbGUiOiJhZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjI4NjQwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNzEiLCJodHRwOi8vbG9jYWxob3N0OjUyOTciLCJodHRwczovL2xvY2FsaG9zdDo3MjMzIl0sIm5iZiI6MTcyODIyMTEyMCwiZXhwIjoxNzM2MTY5OTIwLCJpYXQiOjE3MjgyMjExMjEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.SbqQlMLdrgg2wXB9QmvUdLt2M1exSkhPIzBTgjyUfbk

###

GET http://localhost:5297/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJvaGFuIiwic3ViIjoicm9oYW4iLCJqdGkiOiJkZjc5M2I0ZSIsInJvbGUiOiJwbGF5ZXIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDoyODY0MCIsImh0dHBzOi8vbG9jYWxob3N0OjQ0MzcxIiwiaHR0cDovL2xvY2FsaG9zdDo1Mjk3IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzIzMyJdLCJuYmYiOjE3MjgyMjE2NDcsImV4cCI6MTczNjE3MDQ0NywiaWF0IjoxNzI4MjIxNjQ4LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.DP45BAX3wU8mpGLUTK2xw6WmG8KHFgWgxhr4YNACaoI