GET http://localhost:5297/playergames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InJvaGFuIiwic3ViIjoicm9oYW4iLCJqdGkiOiI3OGE3ODk0MyIsInJvbGUiOiJhZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjI4NjQwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNzEiLCJodHRwOi8vbG9jYWxob3N0OjUyOTciLCJodHRwczovL2xvY2FsaG9zdDo3MjMzIl0sIm5iZiI6MTcyODIyMTEyMCwiZXhwIjoxNzM2MTY5OTIwLCJpYXQiOjE3MjgyMjExMjEsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.SbqQlMLdrgg2wXB9QmvUdLt2M1exSkhPIzBTgjyUfbk

###

GET http://localhost:5297/mygames
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiNGFkNTNkYjEiLCJyb2xlIjoicGxheWVyIiwic3Vic2NyaXB0aW9uIjoiZ29sZCIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjI4NjQwIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNzEiLCJodHRwOi8vbG9jYWxob3N0OjUyOTciLCJodHRwczovL2xvY2FsaG9zdDo3MjMzIl0sIm5iZiI6MTcyODIyMjQyMSwiZXhwIjoxNzM2MTcxMjIxLCJpYXQiOjE3MjgyMjI0MjIsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.N41i0ySotbKaE5k84We3EUrGsAH1jl3EeLHU9FA6Xz0